### ISSUE TITLE
Add link to atom feed in the header for autodiscovery

### ISSUE THREAD

**Issue by florianjacob** [pyfisch/pyfisch.github.io#1]
Hi there! I enjoyed your first article and wanted to subscribe to your blog, but my browser's subscribe button was greyed out. Luckily I still found the atom link at the bottom of the page, though. :wink:

Maybe you want to add something like this in your `<head>`, so that browsers and feeds readers can discover the feed url automatically:

```
<link href="/feed.xml" rel="alternate" title="Pyfisch's blog" type="application/atom+xml">
```

Cheers! :+1:

**Comment by pyfisch** [comment]
Hi Florian,

I've decided to move the blog to a shared hoster with my own domain. In a few days I will have access to the domain name and move the blog. It does not make sense to add this function now because it will be broken anyways but I will add it on the new site.

**Comment by florianjacob** [comment]
Nice, :+1: for your own domain. :smile:
